// Code generated by protoc-gen-go. DO NOT EDIT.
// source: shared/NullableTypes.proto

package NullableTypes

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NullableString struct {
	// Types that are valid to be assigned to String_:
	//	*NullableString_Value
	String_              isNullableString_String_ `protobuf_oneof:"string"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *NullableString) Reset()         { *m = NullableString{} }
func (m *NullableString) String() string { return proto.CompactTextString(m) }
func (*NullableString) ProtoMessage()    {}
func (*NullableString) Descriptor() ([]byte, []int) {
	return fileDescriptor_NullableTypes_0ea9e85a20b18b78, []int{0}
}
func (m *NullableString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NullableString.Unmarshal(m, b)
}
func (m *NullableString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NullableString.Marshal(b, m, deterministic)
}
func (dst *NullableString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NullableString.Merge(dst, src)
}
func (m *NullableString) XXX_Size() int {
	return xxx_messageInfo_NullableString.Size(m)
}
func (m *NullableString) XXX_DiscardUnknown() {
	xxx_messageInfo_NullableString.DiscardUnknown(m)
}

var xxx_messageInfo_NullableString proto.InternalMessageInfo

type isNullableString_String_ interface {
	isNullableString_String_()
}

type NullableString_Value struct {
	Value string `protobuf:"bytes,1,opt,name=value,proto3,oneof"`
}

func (*NullableString_Value) isNullableString_String_() {}

func (m *NullableString) GetString_() isNullableString_String_ {
	if m != nil {
		return m.String_
	}
	return nil
}

func (m *NullableString) GetValue() string {
	if x, ok := m.GetString_().(*NullableString_Value); ok {
		return x.Value
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*NullableString) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _NullableString_OneofMarshaler, _NullableString_OneofUnmarshaler, _NullableString_OneofSizer, []interface{}{
		(*NullableString_Value)(nil),
	}
}

func _NullableString_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*NullableString)
	// string
	switch x := m.String_.(type) {
	case *NullableString_Value:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Value)
	case nil:
	default:
		return fmt.Errorf("NullableString.String_ has unexpected type %T", x)
	}
	return nil
}

func _NullableString_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*NullableString)
	switch tag {
	case 1: // string.value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.String_ = &NullableString_Value{x}
		return true, err
	default:
		return false, nil
	}
}

func _NullableString_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*NullableString)
	// string
	switch x := m.String_.(type) {
	case *NullableString_Value:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Value)))
		n += len(x.Value)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type NullableDouble struct {
	// Types that are valid to be assigned to Double:
	//	*NullableDouble_Value
	Double               isNullableDouble_Double `protobuf_oneof:"double"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *NullableDouble) Reset()         { *m = NullableDouble{} }
func (m *NullableDouble) String() string { return proto.CompactTextString(m) }
func (*NullableDouble) ProtoMessage()    {}
func (*NullableDouble) Descriptor() ([]byte, []int) {
	return fileDescriptor_NullableTypes_0ea9e85a20b18b78, []int{1}
}
func (m *NullableDouble) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NullableDouble.Unmarshal(m, b)
}
func (m *NullableDouble) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NullableDouble.Marshal(b, m, deterministic)
}
func (dst *NullableDouble) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NullableDouble.Merge(dst, src)
}
func (m *NullableDouble) XXX_Size() int {
	return xxx_messageInfo_NullableDouble.Size(m)
}
func (m *NullableDouble) XXX_DiscardUnknown() {
	xxx_messageInfo_NullableDouble.DiscardUnknown(m)
}

var xxx_messageInfo_NullableDouble proto.InternalMessageInfo

type isNullableDouble_Double interface {
	isNullableDouble_Double()
}

type NullableDouble_Value struct {
	Value float64 `protobuf:"fixed64,1,opt,name=value,proto3,oneof"`
}

func (*NullableDouble_Value) isNullableDouble_Double() {}

func (m *NullableDouble) GetDouble() isNullableDouble_Double {
	if m != nil {
		return m.Double
	}
	return nil
}

func (m *NullableDouble) GetValue() float64 {
	if x, ok := m.GetDouble().(*NullableDouble_Value); ok {
		return x.Value
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*NullableDouble) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _NullableDouble_OneofMarshaler, _NullableDouble_OneofUnmarshaler, _NullableDouble_OneofSizer, []interface{}{
		(*NullableDouble_Value)(nil),
	}
}

func _NullableDouble_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*NullableDouble)
	// double
	switch x := m.Double.(type) {
	case *NullableDouble_Value:
		b.EncodeVarint(1<<3 | proto.WireFixed64)
		b.EncodeFixed64(math.Float64bits(x.Value))
	case nil:
	default:
		return fmt.Errorf("NullableDouble.Double has unexpected type %T", x)
	}
	return nil
}

func _NullableDouble_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*NullableDouble)
	switch tag {
	case 1: // double.value
		if wire != proto.WireFixed64 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed64()
		m.Double = &NullableDouble_Value{math.Float64frombits(x)}
		return true, err
	default:
		return false, nil
	}
}

func _NullableDouble_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*NullableDouble)
	// double
	switch x := m.Double.(type) {
	case *NullableDouble_Value:
		n += 1 // tag and wire
		n += 8
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type NullableBool struct {
	// Types that are valid to be assigned to Bool:
	//	*NullableBool_Value
	Bool                 isNullableBool_Bool `protobuf_oneof:"bool"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *NullableBool) Reset()         { *m = NullableBool{} }
func (m *NullableBool) String() string { return proto.CompactTextString(m) }
func (*NullableBool) ProtoMessage()    {}
func (*NullableBool) Descriptor() ([]byte, []int) {
	return fileDescriptor_NullableTypes_0ea9e85a20b18b78, []int{2}
}
func (m *NullableBool) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NullableBool.Unmarshal(m, b)
}
func (m *NullableBool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NullableBool.Marshal(b, m, deterministic)
}
func (dst *NullableBool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NullableBool.Merge(dst, src)
}
func (m *NullableBool) XXX_Size() int {
	return xxx_messageInfo_NullableBool.Size(m)
}
func (m *NullableBool) XXX_DiscardUnknown() {
	xxx_messageInfo_NullableBool.DiscardUnknown(m)
}

var xxx_messageInfo_NullableBool proto.InternalMessageInfo

type isNullableBool_Bool interface {
	isNullableBool_Bool()
}

type NullableBool_Value struct {
	Value bool `protobuf:"varint,1,opt,name=value,proto3,oneof"`
}

func (*NullableBool_Value) isNullableBool_Bool() {}

func (m *NullableBool) GetBool() isNullableBool_Bool {
	if m != nil {
		return m.Bool
	}
	return nil
}

func (m *NullableBool) GetValue() bool {
	if x, ok := m.GetBool().(*NullableBool_Value); ok {
		return x.Value
	}
	return false
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*NullableBool) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _NullableBool_OneofMarshaler, _NullableBool_OneofUnmarshaler, _NullableBool_OneofSizer, []interface{}{
		(*NullableBool_Value)(nil),
	}
}

func _NullableBool_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*NullableBool)
	// bool
	switch x := m.Bool.(type) {
	case *NullableBool_Value:
		t := uint64(0)
		if x.Value {
			t = 1
		}
		b.EncodeVarint(1<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case nil:
	default:
		return fmt.Errorf("NullableBool.Bool has unexpected type %T", x)
	}
	return nil
}

func _NullableBool_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*NullableBool)
	switch tag {
	case 1: // bool.value
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Bool = &NullableBool_Value{x != 0}
		return true, err
	default:
		return false, nil
	}
}

func _NullableBool_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*NullableBool)
	// bool
	switch x := m.Bool.(type) {
	case *NullableBool_Value:
		n += 1 // tag and wire
		n += 1
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type NullableTimestamp struct {
	// Types that are valid to be assigned to Timestamp:
	//	*NullableTimestamp_Value
	Timestamp            isNullableTimestamp_Timestamp `protobuf_oneof:"timestamp"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *NullableTimestamp) Reset()         { *m = NullableTimestamp{} }
func (m *NullableTimestamp) String() string { return proto.CompactTextString(m) }
func (*NullableTimestamp) ProtoMessage()    {}
func (*NullableTimestamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_NullableTypes_0ea9e85a20b18b78, []int{3}
}
func (m *NullableTimestamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NullableTimestamp.Unmarshal(m, b)
}
func (m *NullableTimestamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NullableTimestamp.Marshal(b, m, deterministic)
}
func (dst *NullableTimestamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NullableTimestamp.Merge(dst, src)
}
func (m *NullableTimestamp) XXX_Size() int {
	return xxx_messageInfo_NullableTimestamp.Size(m)
}
func (m *NullableTimestamp) XXX_DiscardUnknown() {
	xxx_messageInfo_NullableTimestamp.DiscardUnknown(m)
}

var xxx_messageInfo_NullableTimestamp proto.InternalMessageInfo

type isNullableTimestamp_Timestamp interface {
	isNullableTimestamp_Timestamp()
}

type NullableTimestamp_Value struct {
	Value *timestamp.Timestamp `protobuf:"bytes,1,opt,name=value,proto3,oneof"`
}

func (*NullableTimestamp_Value) isNullableTimestamp_Timestamp() {}

func (m *NullableTimestamp) GetTimestamp() isNullableTimestamp_Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *NullableTimestamp) GetValue() *timestamp.Timestamp {
	if x, ok := m.GetTimestamp().(*NullableTimestamp_Value); ok {
		return x.Value
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*NullableTimestamp) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _NullableTimestamp_OneofMarshaler, _NullableTimestamp_OneofUnmarshaler, _NullableTimestamp_OneofSizer, []interface{}{
		(*NullableTimestamp_Value)(nil),
	}
}

func _NullableTimestamp_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*NullableTimestamp)
	// timestamp
	switch x := m.Timestamp.(type) {
	case *NullableTimestamp_Value:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Value); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("NullableTimestamp.Timestamp has unexpected type %T", x)
	}
	return nil
}

func _NullableTimestamp_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*NullableTimestamp)
	switch tag {
	case 1: // timestamp.value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(timestamp.Timestamp)
		err := b.DecodeMessage(msg)
		m.Timestamp = &NullableTimestamp_Value{msg}
		return true, err
	default:
		return false, nil
	}
}

func _NullableTimestamp_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*NullableTimestamp)
	// timestamp
	switch x := m.Timestamp.(type) {
	case *NullableTimestamp_Value:
		s := proto.Size(x.Value)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*NullableString)(nil), "NullableString")
	proto.RegisterType((*NullableDouble)(nil), "NullableDouble")
	proto.RegisterType((*NullableBool)(nil), "NullableBool")
	proto.RegisterType((*NullableTimestamp)(nil), "NullableTimestamp")
}

func init() {
	proto.RegisterFile("shared/NullableTypes.proto", fileDescriptor_NullableTypes_0ea9e85a20b18b78)
}

var fileDescriptor_NullableTypes_0ea9e85a20b18b78 = []byte{
	// 227 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0xcf, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x06, 0x60, 0x03, 0x1a, 0xda, 0xa9, 0x08, 0xf6, 0x20, 0x92, 0x8b, 0x92, 0x93, 0x88, 0x4c,
	0x20, 0xbe, 0x41, 0xf0, 0xe0, 0xc9, 0x83, 0xf6, 0x05, 0x76, 0xd3, 0x49, 0x0c, 0xcc, 0x66, 0xc2,
	0xce, 0xae, 0xa0, 0x4f, 0x2f, 0x24, 0x24, 0x6d, 0x8e, 0x03, 0xff, 0xf7, 0x33, 0x3f, 0x64, 0xfa,
	0x6d, 0x3c, 0x1d, 0x8b, 0x8f, 0xc8, 0x6c, 0x2c, 0xd3, 0xe1, 0x77, 0x20, 0xc5, 0xc1, 0x4b, 0x90,
	0xec, 0xa1, 0x15, 0x69, 0x99, 0x8a, 0xf1, 0xb2, 0xb1, 0x29, 0x42, 0xe7, 0x48, 0x83, 0x71, 0xc3,
	0x14, 0xc8, 0x4b, 0xb8, 0x99, 0xdd, 0x57, 0xf0, 0x5d, 0xdf, 0xee, 0xef, 0xe0, 0xea, 0xc7, 0x70,
	0xa4, 0xfb, 0xe4, 0x31, 0x79, 0xda, 0xbe, 0x5f, 0x7c, 0x4e, 0x67, 0xb5, 0x81, 0x54, 0xc7, 0xc4,
	0xb9, 0x79, 0x93, 0x68, 0x99, 0xd6, 0x26, 0x59, 0x99, 0xe3, 0x98, 0xc8, 0x11, 0xae, 0x67, 0x53,
	0x89, 0xf0, 0x5a, 0x6c, 0x4e, 0x22, 0x85, 0x4b, 0x2b, 0xc2, 0xf9, 0x01, 0x6e, 0x97, 0x3d, 0xf3,
	0xcb, 0xfb, 0xf2, 0x1c, 0xed, 0xca, 0x0c, 0xa7, 0x75, 0x38, 0xaf, 0xc3, 0x25, 0x7a, 0x2a, 0xdc,
	0xc1, 0x76, 0xd9, 0x5c, 0xbd, 0xc0, 0x73, 0x2d, 0x0e, 0x5d, 0x57, 0x7b, 0x51, 0x69, 0x02, 0x9a,
	0xbf, 0xe8, 0x09, 0x9b, 0xd8, 0xd7, 0xa1, 0x93, 0x5e, 0xd1, 0x0f, 0x35, 0x3a, 0x52, 0x35, 0x2d,
	0xa9, 0x4d, 0xc7, 0xde, 0xd7, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0x51, 0xa1, 0xe5, 0xe1, 0x61,
	0x01, 0x00, 0x00,
}
