// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// isNullableBool_Bool is an autogenerated mock type for the isNullableBool_Bool type
type isNullableBool_Bool struct {
	mock.Mock
}

// isNullableBool_Bool provides a mock function with given fields:
func (_m *isNullableBool_Bool) isNullableBool_Bool() {
	_m.Called()
}
