// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// isTypedData_Data is an autogenerated mock type for the isTypedData_Data type
type isTypedData_Data struct {
	mock.Mock
}

// isTypedData_Data provides a mock function with given fields:
func (_m *isTypedData_Data) isTypedData_Data() {
	_m.Called()
}
