// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import rpc "github.com/graphql-editor/azure-functions-golang-worker/rpc"
import worker "github.com/graphql-editor/azure-functions-golang-worker/worker"

// Channel is an autogenerated mock type for the Channel type
type Channel struct {
	mock.Mock
}

// FileChangeEventRequest provides a mock function with given fields: requestID, msg
func (_m *Channel) FileChangeEventRequest(requestID string, msg *rpc.FileChangeEventRequest) {
	_m.Called(requestID, msg)
}

// FunctionEnvironmentReloadRequest provides a mock function with given fields: requestID, msg
func (_m *Channel) FunctionEnvironmentReloadRequest(requestID string, msg *rpc.FunctionEnvironmentReloadRequest) {
	_m.Called(requestID, msg)
}

// FunctionLoadRequest provides a mock function with given fields: requestID, msg
func (_m *Channel) FunctionLoadRequest(requestID string, msg *rpc.FunctionLoadRequest) {
	_m.Called(requestID, msg)
}

// Heartbeat provides a mock function with given fields: requestID, msg
func (_m *Channel) Heartbeat(requestID string, msg *rpc.WorkerHeartbeat) {
	_m.Called(requestID, msg)
}

// InitRequest provides a mock function with given fields: requestID, msg
func (_m *Channel) InitRequest(requestID string, msg *rpc.WorkerInitRequest) {
	_m.Called(requestID, msg)
}

// InvocationCancel provides a mock function with given fields: requestID, msg
func (_m *Channel) InvocationCancel(requestID string, msg *rpc.InvocationCancel) {
	_m.Called(requestID, msg)
}

// InvocationRequest provides a mock function with given fields: requestID, msg
func (_m *Channel) InvocationRequest(requestID string, msg *rpc.InvocationRequest) {
	_m.Called(requestID, msg)
}

// SetEventStream provides a mock function with given fields: _a0
func (_m *Channel) SetEventStream(_a0 worker.Sender) {
	_m.Called(_a0)
}

// SetLoader provides a mock function with given fields: _a0
func (_m *Channel) SetLoader(_a0 worker.Loader) {
	_m.Called(_a0)
}

// StartStream provides a mock function with given fields: requestID, msg
func (_m *Channel) StartStream(requestID string, msg *rpc.StartStream) {
	_m.Called(requestID, msg)
}

// StatusRequest provides a mock function with given fields: requestID, msg
func (_m *Channel) StatusRequest(requestID string, msg *rpc.WorkerStatusRequest) {
	_m.Called(requestID, msg)
}

// Terminate provides a mock function with given fields: requestID, msg
func (_m *Channel) Terminate(requestID string, msg *rpc.WorkerTerminate) {
	_m.Called(requestID, msg)
}
