// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import rpc "github.com/graphql-editor/azure-functions-golang-worker/rpc"

// EventStream is an autogenerated mock type for the EventStream type
type EventStream struct {
	mock.Mock
}

// Recv provides a mock function with given fields:
func (_m *EventStream) Recv() (*rpc.StreamingMessage, bool) {
	ret := _m.Called()

	var r0 *rpc.StreamingMessage
	if rf, ok := ret.Get(0).(func() *rpc.StreamingMessage); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rpc.StreamingMessage)
		}
	}

	var r1 bool
	if rf, ok := ret.Get(1).(func() bool); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// Send provides a mock function with given fields: _a0
func (_m *EventStream) Send(_a0 *rpc.StreamingMessage) {
	_m.Called(_a0)
}

// Start provides a mock function with given fields:
func (_m *EventStream) Start() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Stop provides a mock function with given fields:
func (_m *EventStream) Stop() {
	_m.Called()
}
