// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import api "github.com/graphql-editor/azure-functions-golang-worker/api"
import context "context"
import mock "github.com/stretchr/testify/mock"

// Function is an autogenerated mock type for the Function type
type Function struct {
	mock.Mock
}

// Run provides a mock function with given fields: _a0, _a1
func (_m *Function) Run(_a0 context.Context, _a1 api.Logger) {
	_m.Called(_a0, _a1)
}
