// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import rpc "github.com/graphql-editor/azure-functions-golang-worker/rpc"

// FunctionRpcServer is an autogenerated mock type for the FunctionRpcServer type
type FunctionRpcServer struct {
	mock.Mock
}

// EventStream provides a mock function with given fields: _a0
func (_m *FunctionRpcServer) EventStream(_a0 rpc.FunctionRpc_EventStreamServer) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(rpc.FunctionRpc_EventStreamServer) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
