// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// isNullableString_String_ is an autogenerated mock type for the isNullableString_String_ type
type isNullableString_String_ struct {
	mock.Mock
}

// isNullableString_String_ provides a mock function with given fields:
func (_m *isNullableString_String_) isNullableString_String_() {
	_m.Called()
}
