// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// isNullableDouble_Double is an autogenerated mock type for the isNullableDouble_Double type
type isNullableDouble_Double struct {
	mock.Mock
}

// isNullableDouble_Double provides a mock function with given fields:
func (_m *isNullableDouble_Double) isNullableDouble_Double() {
	_m.Called()
}
