// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// isNullableTimestamp_Timestamp is an autogenerated mock type for the isNullableTimestamp_Timestamp type
type isNullableTimestamp_Timestamp struct {
	mock.Mock
}

// isNullableTimestamp_Timestamp provides a mock function with given fields:
func (_m *isNullableTimestamp_Timestamp) isNullableTimestamp_Timestamp() {
	_m.Called()
}
