// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// isStreamingMessage_Content is an autogenerated mock type for the isStreamingMessage_Content type
type isStreamingMessage_Content struct {
	mock.Mock
}

// isStreamingMessage_Content provides a mock function with given fields:
func (_m *isStreamingMessage_Content) isStreamingMessage_Content() {
	_m.Called()
}
