// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import rpc "github.com/graphql-editor/azure-functions-golang-worker/rpc"

// Marshaler is an autogenerated mock type for the Marshaler type
type Marshaler struct {
	mock.Mock
}

// Marshal provides a mock function with given fields:
func (_m *Marshaler) Marshal() (*rpc.TypedData, error) {
	ret := _m.Called()

	var r0 *rpc.TypedData
	if rf, ok := ret.Get(0).(func() *rpc.TypedData); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rpc.TypedData)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
