// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import api "github.com/graphql-editor/azure-functions-golang-worker/api"
import context "context"
import mock "github.com/stretchr/testify/mock"

// ReturnFunction is an autogenerated mock type for the ReturnFunction type
type ReturnFunction struct {
	mock.Mock
}

// Run provides a mock function with given fields: _a0, _a1
func (_m *ReturnFunction) Run(_a0 context.Context, _a1 api.Logger) interface{} {
	ret := _m.Called(_a0, _a1)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(context.Context, api.Logger) interface{}); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}
