// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import rpc "github.com/graphql-editor/azure-functions-golang-worker/rpc"

// Sender is an autogenerated mock type for the Sender type
type Sender struct {
	mock.Mock
}

// Send provides a mock function with given fields: _a0
func (_m *Sender) Send(_a0 *rpc.StreamingMessage) {
	_m.Called(_a0)
}
