// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import api "github.com/graphql-editor/azure-functions-golang-worker/api"
import mock "github.com/stretchr/testify/mock"
import reflect "reflect"
import worker "github.com/graphql-editor/azure-functions-golang-worker/worker"

// TypeLoader is an autogenerated mock type for the TypeLoader type
type TypeLoader struct {
	mock.Mock
}

// GetFunctionType provides a mock function with given fields: _a0, _a1
func (_m *TypeLoader) GetFunctionType(_a0 worker.FunctionInfo, _a1 api.Logger) (reflect.Type, error) {
	ret := _m.Called(_a0, _a1)

	var r0 reflect.Type
	if rf, ok := ret.Get(0).(func(worker.FunctionInfo, api.Logger) reflect.Type); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(reflect.Type)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(worker.FunctionInfo, api.Logger) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
