// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import rpc "github.com/graphql-editor/azure-functions-golang-worker/rpc"

// Unmarshaler is an autogenerated mock type for the Unmarshaler type
type Unmarshaler struct {
	mock.Mock
}

// Unmarshal provides a mock function with given fields: _a0
func (_m *Unmarshaler) Unmarshal(_a0 *rpc.TypedData) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*rpc.TypedData) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
